// Mirrored from [myevals-dotnet-backend/MyEvaluations.Business.Security/CommonTypes.cs](https://github.com/myevaluations/myevals-dotnet-backend/blob/master/MyEvaluations.Business.Security/CommonTypes.cs)
// File is also included in [myevals-nodejs-backend/src/mssql/enums/sub-modules.ts](https://github.com/myevaluations/myevals-nodejs-backend/blob/main/src/mssql/enums/sub-module.ts)
export enum SubModule {
  None = -1,
  Users = 1,
  Departments = 2,
  Institutions = 3,
  DepartmentLinks = 4,
  Roles = 5,
  //Added by Mahesh
  MailBounce = 1265,
  AuditTrail = 6,
  GMEAdmin = 7,
  UserMove = 617,
  //DutyHours SubModules
  Rotations = 8,
  Activities = 9,
  ComplianceSettings = 10,
  RotationDutyHourlinks = 11,
  SyncAMIONUsers = 12,
  SyncAMIONRotations = 13,
  SyncAMIONClinics = 14,
  SyncAMIONCallServices = 15,
  DutyHourBlocks = 16,
  RecordofRotationsReport = 17,
  DutyHourComplianceReport = 18,
  DutyHourSummaryComplianceReport = 19,
  DetailedDutyHoursReport = 20,
  DailySummaryDutyHoursReport = 21,
  WeeklySummaryDutyHoursReport = 22,
  ReviewComments = 151,
  DutyHoursAdmins = 152,
  DefaultProgramDutyHourRules = 153,
  MyScheduleDetails = 154,
  DutyHoursExportData = 155,
  ViolationExplanation = 156,
  DutyHourCompletionReport = 157,
  DutyHourDiscrepancyReport = 158,
  RetrieveOnCallSchedules = 159,
  DutyHoursSetup = 160,
  InstitutionalDHComplianceReport = 161,
  InstitutionalDHCompletionReport = 162,
  InstitutionalDHScheduleDiscrepancyReport = 163,
  ConferenceImporting = 680,
  ManageLinkedDepartment = 722,
  ManageVerifiedDutyHours = 1224,
  LockClinicalHoursModifications = 1255,
  RecordofRotatorsReport = 1263,
  ManageSchedules = 1274,
  ScheduleSettings = 1275,
  ScheduleRequirementsReport = 1276,
  RankOrderCompletionStatusReport = 1277,
  ManageShiftNames = 1278,
  ManageSiteNames = 1279,
  ManageCampusLocations = 1280,
  AssociateSitestoRotations = 1281,
  ScheduleImporting = 1282,
  ManualScheduleImporting = 1283,
  DefineCohortScheduleGrid = 1284,
  AssignTraineestoCampusCohort = 1285,
  AllocateTraineePositionsbyRotationSite = 1286,
  ScheduleRankOrderSubmission = 1287,
  ConferenceSettings = 1288,

  // Conference Sub Module
  Conferences = 23,
  ConferenceSchedules = 24,
  ConferenceAttendance = 25,
  ConferenceGroupParticipants = 26,
  Clinics = 27,
  MonthlyConferenceScheduleReport = 28,
  DetailedConferencesTrackingReport = 29,
  SummaryConferencesTrackingReport = 30,
  ManageConferenceEvaluations = 623,
  ManageConferenceQuestions = 624,
  IndividualConferenceEvaluationReport = 625,
  SummaryConferenceEvaluationReport = 626,
  EditSystemCategory = 762,
  EditConferenceTopicCategory = 763,
  EditCMETrackingSystemCategory = 765, //Added by Amit 10/20/2015 for CME-Tracking Topic Category
  EditCMETrackingTopicCategory = 766, //Added by Amit 10/20/2015
  // TimeSheet submodule
  SubmitReviewDutyHours = 31,
  ClinicConferenceReports = 757,
  WebADSScholarlyActivityImporting = 1221,
  SingleSignOnSettings = 1236,

  //Procedures submodules
  Errors = 32,
  SubmitProcedures = 33,
  ErrorCategories = 34,
  Supervisors = 35,
  Procedures = 36,
  Fields = 37,
  FieldOptions = 38,
  ProcedureImport = 39,
  ProcedureExport = 40,
  IndividualProceduresReport = 41,
  SummaryProceduresReport = 42,
  ProcedureTestingPerformanceReport = 43,
  DepartmentProceduresReport = 44,
  PendingProceduresRequiredReport = 45,
  PendingAuthorizationsReport = 46,
  ErrorsReport = 47,
  ModifyProcedures = 618,
  SupervisionRequirements = 81,
  ManageDefaultCaselogCategories = 1223,
  DefaultAPECaselogCategories = 1227,
  DefaultProgramParticipations = 1226,
  ManageAPEResidentRoles = 1225,
  //Patient Log Submodules
  PatientLog = 48,
  CaseReview = 49,
  PatientLogSupervisors = 50,
  PatientLogFields = 52,
  PatientLogFieldOptions = 53,
  PatientLogImport = 54,
  PatientLogExport = 55,
  LocationNames = 56,
  EncounterTypes = 57,
  DXClassifications = 58,
  PatientLogDepartmentReport = 59,
  PatientLogDetailedReport = 60,
  PatientLogSummaryReport = 61,
  PatientLogDiagnosisReport = 62,
  PatientLogDXDepartmentReport = 63,
  PatientLogByCategoryReport = 64,

  //Learning Assignment Submodules
  LearningAssignment = 65,
  Literature = 66,
  SubmitAssignment = 67,
  ReviewAssignment = 68,
  DetailedAssignmentReport = 69,
  LedgerAssignmentReport = 70,
  LearningAssignmentAdmins = 71,
  PastDueAdminEmails = 743,

  //Evaluations
  EvaluationsTemplate = 72,
  AnswerScales = 73,
  Questions = 74,
  QuestionGroups = 75,
  DescriptiveCriteria = 76,
  EvaluationAssignments = 77,
  DuplicateEvaluationAssignments = 752,
  ExportEvaluationData = 78,
  CompleteEvaluations = 79,
  CompleteEvaluationsByProxy = 738,
  ManageAdministrativeSettings = 740,
  EvaluationsRotations = 80,
  ReviewEvaluation = 82,
  FileEvaluation = 83,
  VoluntaryEvaluation = 84,
  AnswerScalesShared = 605,
  DefaultProgramMilestoneRules = 622,
  ManageOutcomeNarratives = 647,
  DefaultProgramOutcomeRules = 648,
  GAReview = 674,
  CommentsOptional = 675,
  Confidential = 676,
  Anonymity = 677,
  SetupMilestonePeriods = 681,
  DefaultSetupMilestonePeriods = 691,
  MilestoneGroup = 682,
  DefaultMilestoneNarrativeSortOrder = 692,
  MilestoneNarrativeSortOrder = 693,
  CurricularAssessmentWorksheet = 712,
  CurricularMilestoneReport = 713,
  MilestoneNarrativeReport = 714,
  ManageGroupParticipants = 716,
  ShareEvaluationTemplates = 717,
  CurricularMilestoneMapping = 718,
  MilestonePerformanceMapping = 719,
  ManageNationalAverages = 748,
  ManageMilestoneReview = 749,
  MilestonePIPAccess = 1266,
  DefaultMilestonePIPAccess = 1267,
  PIPInbox = 1268,
  LogOfEvaluationAssignments = 1000,
  TemplateUnPublish = 729,
  ManageRotationRequirements = 731,
  DefaultRotationRequirements = 732,
  RotationPerformanceReport = 759,
  ViewRotationRequirements = 760,
  WorksheetConfidentialComments = 737,
  ImportMilestoneNarratives = 739,
  WorksheetTimeAccess = 746,
  MilestoneLedgerofAssessments = 747,
  MilestoneSetup = 750,
  MilestoneRoundingRules = 751,
  AddAPEGroup = 753,
  ReserveQuestionCode = 761,
  DefaultAnnualProgramEvaluationCategories = 1204,
  AnnualProgramEvaluationCategories = 1203,
  ManageOverallClinicalCompetence = 764,
  APESpecific = 1208,
  InstitutionalAnnualProgramReport = 1210,
  AnnualProgramReport = 1211, //Added by Amit 8/28/2015 Annual Report for diff. Admin login with privileges
  AnnualProgramEvaluations = 1215,
  ManageACGMESurvey = 767,
  UpdateNarrativeUserScores = 768,
  OnboardingandCredentialingDashboard = 1260,

  //Reports
  IndividualEvaluation = 101,
  SummaryEvaluation = 102,
  SummaryPeertoPeerEvaluation = 103,
  DetailedProgramEvaluation = 104,
  SummaryProgramEvaluation = 105,
  TrendingofPerformance = 106,
  SummaryCompetancy = 107,
  SummaryPerformance = 108,
  OverDueEvaluaions = 109,
  ClosedEvaluaionsReport = 744,
  DeclinedEvaluations = 110,
  CompletetionStatus = 111,
  LedgerofEvaluations = 112,
  EarlyWarningDetailedReport = 113,
  EarlyWarningOverviewReport = 114,
  CommentsReport = 115,
  ProgramComments = 116,
  ClassRank = 117,
  ThreeSixtyEvaluations = 118,
  GradeRegister = 119,
  MPAS712Register = 120,
  PersonalCompleted = 121,
  ACGMEComments = 122,
  ACGMESurvey = 123,
  ACGMEIMSurvey = 124,
  ACGMEPGY3Survey = 125,
  MoodleGradeReport = 126,
  AttendingScoringProfile = 651,
  PreceptorIndividualReport = 668,
  PreceptorLedgerReport = 1209, //Added by Amit 8/11/2015
  PreceptorSummaryTraineeProceduresReport = 667,
  PreceptorIndividualTraineeProcedureReport = 666,
  PreceptorCommentsReport = 665,
  PreceptorOverdueReport = 664,
  PreceptorClosedEvaluationsReport = 745,
  PreceptorSummaryPerformanceReport = 663,
  PreceptorSummaryCompetencyReport = 662,
  PreceptorSummaryEvaluationReport = 661,
  ArchivedReports = 670,
  ManagementReport = 727,
  OptionalConfidentialComments = 730,
  //My Help Sub Modules
  Sections = 401,
  Chapters = 402,
  Pages = 403,
  Contents = 404,

  //My Quiz Sub Modules
  QuizAssignments = 421,
  IntegratedOncallAssignments = 422,
  ManageAssignments = 423,
  DesignaQuiz = 424,
  EditaQuiz = 425,
  ManageQuizQuestions = 426,
  ImportQuizQuestions = 427,
  DetailedQuizAssignmentsReport = 428,
  SummaryQuizPerformanceReport = 429,
  LedgerofQuizAssignmentsReport = 430,
  PendingQuiz = 431,
  CompletedQuiz = 432,
  VoluntaryQuiz = 433,
  ReviewCompletedQuizzes = 601,
  QuizAnalysis = 602,
  ManageQuizTemplates = 434,

  //MyPortfolio subModule
  MyPortfolio = 451,
  ChangePhoto = 723,
  MyPortfolioDocumentDetails = 1246, //Added by Sbharathi for User Access
  //Users SubModule
  ManageUsers = 461,
  AddEditExistingUsers = 1205,
  SyncUsers = 463,
  SelectPreceptors = 464,
  ArchiveorPromoteUsers = 465,
  ArchivedUserList = 466,
  UserImporting = 467,
  DetailedDemographicsReport = 468,
  SummaryDemographicsReport = 469,
  DesignaDataMergeDocument = 470,
  MaskPassword = 603,
  ShowAllUserPasswords = 604,
  GenerateProcedureVerificationURL = 754,
  UserAddedTime = 756,
  ExportToOnCall = 1206,

  //Onboarding and credentialing module
  OnboardingCredentialingSetup = 1200,
  OnboardingCredentialingDashboard = 1201,
  OnboardingCredentialingAssign = 1202,
  OnboardingDocumentationCompletionReport = 1207,
  DashBoardAccess = 1212, //Added by Adilakshmi
  ManageEmailReminderSettings = 1213, //Added by Adilakshmi
  UndoEvaluation = 1214, //Added by Amit 12/3/2015
  OBCBatchMerge = 1217,
  DocumentRestore = 1219,
  ManageDeletedGroups = 1237,
  //OnCall Submodule
  OnCallSubModule = 462,
  SelectRotatingUsers = 660,
  MergeUsers = 669,
  MailHistory = 683,
  UserMoonlightingHistory = 684,
  UserProgramHistory = 685,
  UserSpecialMedicalActivityHistory = 686,
  UserTrainingGapHistory = 687,
  SelectCommitteeMembers = 694,
  UserReportSetting = 726,

  //Mail SubModule
  Mail = 471,

  //CME Tracking Sub Modules
  CmeTemplates = 501,
  CmeEvents = 502,
  CmeEvaluations = 503,
  CmeQuestions = 504,
  CreditTypes = 505,
  Courses = 506,
  CmeAssignments = 507,
  Certificates = 508,
  CompleteCMEEvaluations = 509,
  SummaryEventReport = 510,
  CertificateReport = 511,
  SummaryLedgerofCMECredits = 512,
  DetailedLedgerofCMECredits = 513,

  //Security Module
  AddDiagnosisCategory = 601,
  DetailsSection = 641,
  ConnectivitySection = 642,
  OptionsSection = 643,
  SystemSection = 644,
  PasswordPolicySection = 645,
  LinksSection = 646,
  ManageUserEmailAddresses = 659,
  ManageUserProfile = 671,
  ManageDepartmentLinks = 672,
  PasswordChange = 600,
  ServiceMessage = 673,
  PDAdminInboxSettings = 742,
  ShowDepartmentDropDown = 758,
  TestERASconnection = 1001,

  NewsAndEvents = 678,
  Testimonial = 679,
  EvaluationQuestionCategories = 688,
  BaseEvaluationQuestions = 689,
  Diagnosis = 690,
  UserNameEdit = 720,
  ChangeText = 721,
  SendUserReminderEmails = 725,
  LinkedDepartmentClick = 728,
  UserMovePage = 741,
  ClosedDepartments = 755,
  InstitutionalGA = 1238,

  //Curriculum
  ManageCurriculum = 634,
  ManageCourse = 635,
  ManageTeachingUnits = 636,
  ManageInstructionUnits = 637,
  ManageCurriculumAssignments = 638,
  SearchCurriculum = 639,
  CurriculumReports = 640,

  //Main Module
  Main = 606,
  ShowInbox = 607,
  EvaluationsToReview = 608,
  DepartmentSummaryProfile = 609,
  StaffMenuItems = 610,
  ShowInstitutionDepartments = 611,
  CompleteLearningAssignmentReview = 612,
  LearningAssignmentSubmit = 613,
  EvaluationsToSign = 614,
  PendingProcedures = 615,
  ProcedureCertificate = 616,
  ProceduresToReview = 619,
  PatientCasestoReview = 620,
  SubmitConferencesAttendance = 621,
  TrainingEvent = 627,
  SubmitProcedureLog = 649,
  SubmitPatientLog = 650,
  WebADSCaseLogImporting = 1222,

  QuizToComplete = 653,
  AnonymousEvaluations = 654,
  DutyHourViolationstoReview = 655,
  InterimEvaluationstoReview = 656,

  Messages = 657,

  ShowDashboard = 715,
  SystemImplementation = 1261,
  SetupPagePrimaryEmployerName = 1270,
  EnableInstitutionalAffiliation = 1262,
  MissingMyGMEDemographics = 1269,
  PerformanceArchivedUsers = 1292,
  //Mail Module
  TrainingEventforRegistration = 628,
  AddTrainingEvents = 629,
  Supportcare = 630,
  CustomerSupport = 631,
  TechnicalSupport = 632,
  OnlineMeeting = 633,

  SendManualEmailAssignmentReminders = 658,

  PreceptorRecordofRotationsReport = 733,
  PreceptorDutyHourComplianceReport = 734,
  PreceptorSummaryConferencesTrackingReport = 735,
  PreceptorPatientLogSummaryReport = 736,
  DutyHourUserOverlapVerification = 1220, // Added by rajiv for new page DHUserVerification.aspx
  ProcedureCategories = 1235,
  ManageFileEvaluations = 1239, //Added by Sbharathi on 15/03/2017 for FILE GA Evaluations
  //Added by Sbharathi for GA-Emergency on 16/08/17
  SecurityMain = 1247,
  UsersMenu = 1248,
  EvaluationsMain = 1249,
  QuizMain = 1250,
  CMEMain = 1251,
  CMEAssignMenu = 1252,
  MonitorSynthetics = 1253,
  //Add end by Sbharathi for GA-Emergency on 16/08/17
  // -----Devry------//
  LogActivities = 1241,
  ManageLogActivities = 1242,
  ReviewLoggedActivities = 1243,
  ManageSessionNames = 1244,
  ManageLogActivitiesandRoster = 1245,
  ShowAPLHours = 1254,
  //Added by Sbharathi for REQUEST: Contact information in emails
  ManageContactInformation = 1256,
  ManageBehaviors = 1257,
  ManageCourseObjectives = 1258,
  DeleteUserGrid = 1271, //for delete user grid by swati
  ManageCMESatellitePrograms = 1272,
  ManageCMEConnectivity = 1273,
}
