name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          cache: yarn

      - run: yarn install --frozen-lockfile
        id: npm-install

      - run: npm version ${{ github.event.release.name || inputs.version }} --no-git-tag-version

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify FSH Slack on failure
        if: failure() && github.ref_name == 'main'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "myevals-alerts"
          slack-message: ":red_circle: Workflow *<${{env.GITHUB_WORKFLOW_URL}}|${{github.workflow_ref}}>* failed"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.FSH_SLACK_BOT_TOKEN }}
          GITHUB_WORKFLOW_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
